version: "3"
services:
  node:
    build: ./app
    #image: typetest_node
    environment:
      - PORT=${PORT}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - D_HOST=${D_HOST}
      - D_USER=${D_USER}
      - D_PASSWORD=${D_PASSWORD}
      - D_DATABASE=${D_DATABASE}
      - D_DBPORT=${D_DBPORT}
      - MYSQL_HOST=${MYSQL_HOST}
    ports:
      - "3001:3001"
    depends_on:
      - db
  db:
    build: ./db
    #image: typetest_db
    ports:
      - "3307:3306"
    environment:
      - PORT=${PORT}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - D_HOST=${D_HOST}
      - D_USER=${D_USER}
      - D_PASSWORD=${D_PASSWORD}
      - D_DATABASE=${D_DATABASE}
      - D_DBPORT=${D_DBPORT}
      - MYSQL_HOST=${MYSQL_HOST}
